name: base
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - bcftools=1.9=h5c2b69b_6
  - bedtools=2.29.2=hc088bd4_0
  - biopython=1.76=py36h516909a_0
  - boost=1.70.0=py36h9de70de_1
  - boost-cpp=1.70.0=h8e57a91_2
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py36_0
  - cffi=1.13.2=py36h8022711_0
  - chardet=3.0.4=py36_1003
  - click=7.0=py_0
  - conda=4.8.2=py36_0
  - conda-package-handling=1.6.0=py36h516909a_1
  - crispritz=2.1.1=py36hd739066_0
  - cryptography=2.8=py36h72c5cf5_1
  - curl=7.65.3=hf8cf82a_0
  - cycler=0.10.0=py_2
  - dash=1.7.0=py_0
  - dash-bootstrap-components=0.7.1=py36_0
  - dash-core-components=1.6.0=py_0
  - dash-daq=0.2.2=py_0
  - dash-html-components=1.0.2=py_0
  - dash-renderer=1.2.2=py_0
  - dash-table=4.5.1=py_0
  - dbus=1.13.6=he372182_0
  - expat=2.2.9=he1b5a44_2
  - flask=1.1.1=py_1
  - flask-caching=1.7.1=py_0
  - flask-compress=1.4.0=py_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - future=0.18.2=py36_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=py36h6f030ca_1002
  - gsl=2.5=h294904e_1
  - gst-plugins-base=1.14.5=h0935bb2_1
  - gstreamer=1.14.5=h36ae1b5_1
  - gunicorn=19.9.0=py36_0
  - icu=64.2=he1b5a44_1
  - idna=2.8=py36_1000
  - intervaltree=3.0.2=py_0
  - itsdangerous=1.1.0=py_0
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.1.0=py36hc9558a2_0
  - krb5=1.16.4=h2fd8d38_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libclang=9.0.1=default_hde54327_0
  - libcurl=7.65.3=hda55be3_0
  - libcxx=9.0.1=1
  - libcxxabi=9.0.1=1
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_4
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_openblas
  - libllvm9=9.0.1=hc9558a2_0
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.9.1=hebb1f50_0
  - libxml2=2.9.10=hee79883_0
  - llvm-openmp=8.0.1=hc9558a2_0
  - markupsafe=1.1.1=py36h516909a_0
  - matplotlib=3.1.2=py36_1
  - matplotlib-base=3.1.2=py36h250f245_1
  - more-itertools=8.2.0=py_0
  - ncurses=6.1=hf484d3e_1002
  - nspr=4.24=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.17.5=py36h95a1406_0
  - openmp=8.0.1=0
  - openssl=1.1.1=h7b6447c_0
  - pandas=1.0.0=py36hb3f55d8_0
  - patsy=0.5.1=py_0
  - pcre=8.43=he1b5a44_0
  - perl=5.26.2=h516909a_1006
  - pip=20.0.2=py36_1
  - plotly=4.5.0=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - pycosat=0.6.3=py36h516909a_1002
  - pycparser=2.19=py36_1
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.12.3=py36hcca6a23_1
  - pysocks=1.7.1=py36_0
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyyaml=5.3=py36h516909a_0
  - qt=5.12.5=hd8c4c69_1
  - readline=7.0=hf8c457e_1001
  - requests=2.22.0=py36_1
  - retrying=1.3.3=py_2
  - ruamel_yaml=0.15.80=py36h516909a_1000
  - scikit-learn=0.21.2=py36hcdab131_1
  - scipy=1.4.1=py36h921218d_0
  - setuptools=45.1.0=py36_0
  - six=1.14.0=py36_0
  - sortedcontainers=2.1.0=py_0
  - sqlite=3.30.1=h7b6447c_0
  - statsmodels=0.11.0=py36h516909a_0
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.3=py36h516909a_0
  - tqdm=4.42.0=py_0
  - urllib3=1.25.7=py36_0
  - werkzeug=0.16.1=py_0
  - wheel=0.34.2=py36_0
  - xlrd=1.2.0=py36_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_1001
  - yaml=0.2.2=h516909a_1
  - zip=3.0=h14c3975_1
  - zlib=1.2.11=h516909a_1006
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: /root/miniconda3

